INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE','en','page');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE','it','pagina');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_MODEL','en','page model');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_MODEL','it','modello pagina');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_TITLE','en','page title');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_TITLE','it','titolo pagina');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('RESERVED_AREA','en','Please sign in');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('RESERVED_AREA','it','È necessario autenticarsi');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USERNAME','en','Username');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USERNAME','it','Utente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PASSWORD','en','Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PASSWORD','it','Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SIGNIN','en','Sign in');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SIGNIN','it','Entra');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('WELCOME','en','Welcome');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('WELCOME','it','Benvenuto');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_CREATION','en','Creation date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_CREATION','it','Data creazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_ACCESS_LAST','en','Last access');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_ACCESS_LAST','it','Ultimo accesso');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_PASSWORD_CHANGE_LAST','en','Last change');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_PASSWORD_CHANGE_LAST','it','Ultimo cambio password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('LOGOUT','en','Logout');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('LOGOUT','it','Logout');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_NOT_ALLOWED','en','User not allowed');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_NOT_ALLOWED','it','Utente non autorizzato');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_NOT_FOUND','en','Page not found');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_NOT_FOUND','it','Pagina non trovata');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('GENERIC_ERROR','en','Generic Error');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('GENERIC_ERROR','it','Errore Generico');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_BASIC','it','Normale');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_BASIC','en','Normal');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_MINT','it','Avanzata');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_MINT','en','Advanced');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_BASIC_GOTO','it','Accedi con client normale');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_BASIC_GOTO','en','Go to the administration with normal client');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_MINT_GOTO','it','Accedi con client avanzato');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_MINT_GOTO','en','Go to the administration with advanced client');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DATE_FROM','en','From');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DATE_FROM','it','Da');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DATE_TO','en','To');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DATE_TO','it','A');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('TEXT','en','Text');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('TEXT','it','Testo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ALL','en','All');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ALL','it','Tutte');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NUMBER_FROM','en','From');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NUMBER_FROM','it','Da');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NUMBER_TO','en','To');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NUMBER_TO','it','A');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCES','it','Risorse API');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCES','en','API Resources');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_ERROR','it','Errore');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_ERROR','en','Errors');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE','it','Risorsa');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE','en','Resource');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_DESCRIPTION','it','Descrizione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_DESCRIPTION','en','Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_DETAILS','it','Vai al dettaglio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_DETAILS','en','Go to details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_SERVICE_LIST','it','Elenco Servizi API');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_SERVICE_LIST','en','Service List');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE','it','Servizio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE','en','Service');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_OFF','it','Non Attivo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_OFF','en','Not Active');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_FREE','it','Attivo, Accesso Libero');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_FREE','en','Active, Free Access');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_AUTH','it','Attivo, Utenti Registrati');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_AUTH','en','Active, Registered Users');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_LOCK','it','Metodo Attivo, Utenti Registrati con Autorizzazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_LOCK','en','Active, Registered Users with Permission');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_NA','it','Metodo Non Disponibile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_NA','en','Method Not Available');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_NO_RESOURCES','it','Non ci sono Risorse API disponibili.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_NO_RESOURCES','en','No API Resources available at the moment.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_TABLE_SUMMARY','it','La tabella elenaca le Risorse API disponibile nel sistema. Nome della risorsa, la sua descrizione e lo stato di ciascun metodo.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_TABLE_SUMMARY','en','The table lists the API Resources available in the system. Method name, description, group and the status of each method.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAME','it','Nome');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAME','en','Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAMESPACE','it','Namespace');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAMESPACE','en','Namespace');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_SOURCE','it','Sorgente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_SOURCE','en','Source');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_URI','it','URI');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_URI','en','URI');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_EXTENSION','it','Estensione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_EXTENSION','en','Extension');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_EXTENSION_NOTE','it','''.xml'' per la risposta in formato xml e ''.json'' per la risposta in formato json.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_EXTENSION_NOTE','en','''.xml'' for response in xml format and ''.json'' for json.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_KO','it','Non disponibile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_KO','en','Not available');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD','it','Metodo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD','en','Method');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_OK','it','Disponibile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_OK','en','Available');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTHORIZATION','it','Autorizzazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTHORIZATION','en','Authorization');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_FREE','it','Nessuna, questo metodo è pubblico');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_FREE','en','None, this method is public');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_WITH_PERM','it','Utenti registrati con permesso');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_WITH_PERM','en','Registered users with permission');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_SIMPLE','it','Utenti registrati');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_SIMPLE','en','Registered users');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMAS','it','Schema XML');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMAS','en','XML Schemas');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_REQ','it','Richiesta');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_REQ','en','Request');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_RESP','it','Risposta');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_RESP','en','Response');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTHORIZATION','it','Autorizzazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_FREE','en','Free');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_PARAMS_SUMM','it','Questa tabella mostra i parametri per la richiesta del metodo. Per ciascuno di essi ci sono tre colonne: il nome del parametro, la descrizione del parametro e l''indicazione di obbligatorietà.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_PARAMS_SUMM','en','This table shows the request parameters for this method. For each of them there are three columns: the parameter name, the parameter description and whether if it''s mandatory or not.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_REQUEST_PARAMS','it','Parametri');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_REQUEST_PARAMS','en','Parameters');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_NAME','it','Nome');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_NAME','en','Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_DESCRIPTION','it','Descrizione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_DESCRIPTION','en','Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_REQUIRED','it','Obbligatorio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_REQUIRED','en','Mandatory');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('YES','it','Si');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('YES','en','Yes');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NO','it','No');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NO','en','No');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('BOTH','it','Entrambi');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('BOTH','en','Both');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_LIST','it','Lista delle Risorse API');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_LIST','en','API Resource List');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_PREV','it','Indietro');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_PREV','en','Previous');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_NEXT','it','Ancora');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_NEXT','en','Next');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_FIRST','it','Inizio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_FIRST','en','Start');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_LAST','it','Fine');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_LAST','en','End');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_STEP_BACKWARD','it','Indietro di');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_STEP_BACKWARD','en','Previous');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_STEP_FORWARD','it','Avanti di');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_STEP_FORWARD','en','Next');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CATEGORY','it','Categoria');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CATEGORY','en','Category');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('IGNORE','it','Ignora');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('IGNORE','en','Ignore');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ERRORS','it','Oops! Hai sbagliato qualcosa!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ERRORS','en','Whoops! You''re doing it wrong!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CONFIGURATION','it','Configura il profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CONFIGURATION','en','Edit profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CONFIRM_NEWPASS','it','Conferma nuova password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CONFIRM_NEWPASS','en','Confirm new password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPASSWORD','it','Modifica Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPASSWORD','en','Edit Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPASSWORD_TITLE','it','Modifica Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPASSWORD_TITLE','en','Edit Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPROFILE_TITLE','it','Modifica profilo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPROFILE_TITLE','en','Edit Profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEUP','it','Sposta su');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEUP','en','Move up');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEUP_IN','it','Sposta su in posizione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEUP_IN','en','Move at position');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN','it','Sposta giu');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN','en','Move down');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN_IN','it','Sposta giu in posizione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN_IN','en','Move down at position');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_REMOVE','it','Rimuovi dalla lista');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_REMOVE','en','Remove from list');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_MESSAGE_TITLE_FIELDERRORS','it','Attenzione, si sono verificati i seguenti errori nella compilazione del modulo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_MESSAGE_TITLE_FIELDERRORS','en','Warning, please check the module');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_NEWPASS','it','Nuova password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_NEWPASS','en','New password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_OLDPASSWORD','it','Vecchia password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_OLDPASSWORD','en','Old password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PASSWORD_UPDATED','it','La password è stata aggiornata correttamente.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PASSWORD_UPDATED','en','Your password updated successfully.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN','it','E'' necessario effettuare l''accesso');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN','en','Please login');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN_AGAIN','it','E'' necessario riloggarsi.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN_AGAIN','en','Please logout and login again.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN_TO_EDIT_PASSWORD','it','E'' necessario effettuare l''accesso per cambiare la password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN_TO_EDIT_PASSWORD','en','Please login in order to change your password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PROFILE_UPDATED','it','Profilo aggiornato correttamente.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PROFILE_UPDATED','en','Your profile is now updated.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_SAVE_PASSWORD','it','Salva password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_SAVE_PASSWORD','en','Save password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_SAVE_PROFILE','it','Salva il profilo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_SAVE_PROFILE','en','Save profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ADDITEM_LIST','it','Aggiungi nuovo elemento alla lista');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ADDITEM_LIST','en','Add an element to the list');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_YES','it','Si');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_YES','en','Yes');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_NO','it','No');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_NO','en','No');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_BOTH_YES_AND_NO','it','Indifferente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_BOTH_YES_AND_NO','en','Both');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_SHORT','it','*');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_SHORT','en','*');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_FULL','it','Obbligatorio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_FULL','en','Mandatory');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_SHORT','it','Min');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_SHORT','en','Min');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_FULL','it','Lunghezza Minima');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_FULL','en','Minimum length');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_SHORT','it','Max');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_SHORT','en','Max');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_FULL','it','Lunghezza Massima');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_FULL','en','Maximum length');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CURRENT_USER_WITHOUT_PROFILE','it','Utente corrente senza profilo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CURRENT_USER_WITHOUT_PROFILE','en','Current user without profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_KEY','en','Key');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_KEY','it','Id');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARENT_API','en','Parent API');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARENT_API','it','API Padre');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTHORIZATION','en','Authorization');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_FREE','it','Accesso Libero');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_URI','en','URI');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_URI','it','URI');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS','en','Parameters');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS','it','Parametri');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_WELCOME-I','en','Hello');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_WELCOME-I','it','Ciao');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_ADMINISTRATION-I','en','Administration');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_ADMINISTRATION-I','it','Amministrazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_SIGNOUT-I','en','Sign out');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_SIGNOUT-I','it','Esci');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_SIGNIN-I','en','Sign in');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_SIGNIN-I','it','Accedi');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USER_STATUS_EXPIRED-I','en','Your account has expired!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USER_STATUS_EXPIRED-I','it','Credenziali scadute!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USER_STATUS_CREDENTIALS_INVALID-I','en','Wrong username or password!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USER_STATUS_CREDENTIALS_INVALID-I','it','Le credenziali non sono corrette!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USERNAME-I','en','Username');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USERNAME-I','it','Utente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_PASSWORD-I','en','Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_PASSWORD-I','it','Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_PROFILE_CONFIGURATION-I','en','Edit profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_PROFILE_CONFIGURATION-I','it','Modifica profilo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANGUAGE_I','en','Language');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANGUAGE_I','it','Lingua');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANG_it_I','en','Italiano');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANG_it_I','it','Italiano');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANG_en_I','en','English');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANG_en_I','it','English');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('COPYRIGHT','en','Copyright &copy; My Company YYYY');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('COPYRIGHT','it','Copyright &copy; Mia Azienda AAAA');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PORTAL_TITLE','en','My Portal');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PORTAL_TITLE','it','Il Mio Portale');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_ATTACHMENTS','en','Attachments');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_ATTACHMENTS','it','Allegati');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_LINKS','en','Links');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_LINKS','it','Link');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_READ_MORE','en','View details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_READ_MORE','it','Continua');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH','en','Search');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH','it','Cerca');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_FILTERS_BUTTON','en','Narrow your search');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_FILTERS_BUTTON','it','Filtra ulteriormente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('LIST_VIEWER_EMPTY','en','No result found. Broaden your search and try again!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('LIST_VIEWER_EMPTY','it','Nessun risultato trovato. Imposta dei parametri meno stringenti e prova ancora!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_FIELD','en','The value for field');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_FIELD','it','Il valore del campo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_FORMAT','en','is invalid');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_FORMAT','it','non è corretto');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_RANGE','en','generates an invalid range');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_RANGE','it','genera un range non valido');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('EDIT_THIS_CONTENT','en','Edit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('EDIT_THIS_CONTENT','it','Modifica');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS','en','Search Result');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS','it','Risultati della Ricerca');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCHED_FOR','en','You searched for');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCHED_FOR','it','Hai cercato');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_NOTHING_FOUND','en','No result found. Try another search term!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_NOTHING_FOUND','it','Nessun risultato trovato. Prova a cercare un altro termine!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS_INTRO','en','Found');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS_INTRO','it','Sono stati trovati');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS_OUTRO','en','results. Showing:');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS_OUTRO','it','risultati. Mostrati:');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_SEARCH_TEXT_ALL_WORDS','it','Tutte le parole');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_SEARCH_TEXT_ALL_WORDS','en','All words');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_SEARCH_TEXT_AT_LEAST_ONE_WORD','it','Almeno una parola');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_SEARCH_TEXT_AT_LEAST_ONE_WORD','en','At least one word');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_SEARCH_TEXT_EXACT','it','Frase esatta');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_SEARCH_TEXT_EXACT','en','Exact');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_application_downPayment','en','Down Payment');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_application_downPayment','it','Down Payment');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_application_amortization','en','Mortgage Amortization');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_application_amortization','it','Mortgage Amortization');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_applicant_name','en','Applicant Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_applicant_name','it','Applicant Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_applicant_ssn','en','Social Security Number');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_applicant_ssn','it','Social Security Number');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_applicant_income','en','Annual Income');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_applicant_income','it','Annual Income');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_property_address','en','Property Address');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_property_address','it','Property Address');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_property_price','en','Sale Price');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_property_price','it','Sale Price');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_application','en','APPLICATION');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_application','it','APPLICATION');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_applicant','en','APPLICANT');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_applicant','it','APPLICANT');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_property','en','PROPERTY');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_property','it','PROPERTY');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_TITLE_MortgageApplication','en','PROCESS MORTGAGEAPPLICATION');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_TITLE_MortgageApplication','it','PROCESS MORTGAGEAPPLICATION');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_brokerOverrideTaskOutput','en','BrokerOverrideTaskOutput');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_brokerOverrideTaskOutput','it','BrokerOverrideTaskOutput');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Action Required By','en','Action Required By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Action Required By','it','Action Required By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual Close Date','en','Actual Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual Close Date','it','Actual Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual Remediation Date','en','Actual Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual Remediation Date','it','Actual Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BG Steward','en','BG Steward');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BG Steward','it','BG Steward');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business Glossary Term Category','en','Business Glossary Term Category');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business Glossary Term Category','it','Business Glossary Term Category');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business Glossary Term Name','en','Business Glossary Term Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business Glossary Term Name','it','Business Glossary Term Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BusinessAdministratorGroupId','en','BusinessAdministratorGroupId');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BusinessAdministratorGroupId','it','BusinessAdministratorGroupId');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Close Reason','en','Close Reason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Close Reason','it','Close Reason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Comments','en','Comments');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Comments','it','Comments');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Element Mapping','en','Element Mapping');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Element Mapping','it','Element Mapping');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Description','en','Exception Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Description','it','Exception Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception ID','en','Exception ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception ID','it','Exception ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Severity','en','Exception Severity');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Severity','it','Exception Severity');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Summary','en','Exception Summary');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Summary','it','Exception Summary');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identified Date','en','Identified Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identified Date','it','Identified Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact Amount','en','Impact Amount');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact Amount','it','Impact Amount');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid Associated Dollars','en','Invalid Associated Dollars');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid Associated Dollars','it','Invalid Associated Dollars');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Matrix Rating','en','Matrix Rating');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Matrix Rating','it','Matrix Rating');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Open Page ID','en','Open Page ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Open Page ID','it','Open Page ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation Owner Name','en','Remediation Owner Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation Owner Name','it','Remediation Owner Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule Description','en','Rule Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule Description','it','Rule Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Source System','en','Source System');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Source System','it','Source System');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target Remediation Date','en','Target Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target Remediation Date','it','Target Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated By','en','Updated By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated By','it','Updated By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Date Determined','en','Date Determined');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Date Determined','it','Date Determined');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Escalation Date','en','Escalation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Escalation Date','it','Escalation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Details','en','Exception Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Details','it','Exception Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Owner','en','Exception Owner');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Owner','it','Exception Owner');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Status','en','Exception Status');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception Status','it','Exception Status');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Final Disposition','en','Final Disposition');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Final Disposition','it','Final Disposition');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identifying Process','en','Identifying Process');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identifying Process','it','Identifying Process');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact Description','en','Impact Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact Description','it','Impact Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid Count','en','Invalid Count');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid Count','it','Invalid Count');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_MonitoringReason','en','MonitoringReason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_MonitoringReason','it','MonitoringReason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation Description','en','Remediation Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation Description','it','Remediation Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Root Cause','en','Root Cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Root Cause','it','Root Cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule Name','en','Rule Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule Name','it','Rule Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target Close Date','en','Target Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target Close Date','it','Target Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business Unit','en','Business Unit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business Unit','it','Business Unit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated Date','en','Updated Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated Date','it','Updated Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_ManageEDGDepositFormSustain-taskform','en','ManageEDGDepositFormSustain-taskform');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_ManageEDGDepositFormSustain-taskform','it','ManageEDGDepositFormSustain-taskform');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_TITLE_EDGLoadDepositExceptionsProcess','en','PROCESS EDGLOADDEPOSITEXCEPTIONSPROCESS');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_TITLE_EDGLoadDepositExceptionsProcess','it','PROCESS EDGLOADDEPOSITEXCEPTIONSPROCESS');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_application_downpayment','en','Down Payment');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_application_downpayment','it','Down Payment');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_applicant_annualincome','en','Annual Income');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_applicant_annualincome','it','Annual Income');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_property_age','en','Age of property');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_property_age','it','Age of property');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_property_locale','en','Locale');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_property_locale','it','Locale');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_property_saleprice','en','Sale Price');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_property_saleprice','it','Sale Price');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_TITLE_MortgageApprovalProcess','en','PROCESS MORTGAGEAPPROVALPROCESS');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_TITLE_MortgageApprovalProcess','it','PROCESS MORTGAGEAPPROVALPROCESS');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_inlimit','en','Is mortgage application in limit?');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_inlimit','it','Is mortgage application in limit?');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Application_downpayment','en','Down Payment');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Application_downpayment','it','Down Payment');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Application_amortization','en','Years of amortization');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Application_amortization','it','Years of amortization');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_validationErrorDO_error','en','Error and cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_validationErrorDO_error','it','Error and cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_Application','en','APPLICATION');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_Application','it','APPLICATION');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_validationErrorDO','en','VALIDATIONERRORDO');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_validationErrorDO','it','VALIDATIONERRORDO');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Action_Required_By','en','Action Required By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Action_Required_By','it','Action Required By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_Close_Date','en','Actual Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_Close_Date','it','Actual Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_Remediation_Date','en','Actual Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_Remediation_Date','it','Actual Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BG_Steward','en','BG Steward');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BG_Steward','it','BG Steward');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_Glossary_Term_Category','en','Business Glossary Term Category');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_Glossary_Term_Category','it','Business Glossary Term Category');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_Glossary_Term_Name','en','Business Glossary Term Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_Glossary_Term_Name','it','Business Glossary Term Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Close_Reason','en','Close Reason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Close_Reason','it','Close Reason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Date_Determined','en','Date Determined');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Date_Determined','it','Date Determined');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Element_Mapping','en','Element Mapping');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Element_Mapping','it','Element Mapping');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Escalation_Date','en','Escalation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Escalation_Date','it','Escalation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Description','en','Exception Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Description','it','Exception Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Details','en','Exception Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Details','it','Exception Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_ID','en','Exception ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_ID','it','Exception ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Owner','en','Exception Owner');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Owner','it','Exception Owner');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Severity','en','Exception Severity');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Severity','it','Exception Severity');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Status','en','Exception Status');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Status','it','Exception Status');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Summary','en','Exception Summary');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_Summary','it','Exception Summary');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Final_Disposition','en','Final Disposition');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Final_Disposition','it','Final Disposition');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identified_Date','en','Identified Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identified_Date','it','Identified Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identifying_Process','en','Identifying Process');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identifying_Process','it','Identifying Process');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_Amount','en','Impact Amount');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_Amount','it','Impact Amount');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_Description','en','Impact Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_Description','it','Impact Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_Associated_Dollars','en','Invalid Associated Dollars');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_Associated_Dollars','it','Invalid Associated Dollars');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_Count','en','Invalid Count');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_Count','it','Invalid Count');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Matrix_Rating','en','Matrix Rating');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Matrix_Rating','it','Matrix Rating');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Open_Page_ID','en','Open Page ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Open_Page_ID','it','Open Page ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_Description','en','Remediation Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_Description','it','Remediation Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_Owner_Name','en','Remediation Owner Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_Owner_Name','it','Remediation Owner Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Root_Cause','en','Root Cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Root_Cause','it','Root Cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_Description','en','Rule Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_Description','it','Rule Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_Name','en','Rule Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_Name','it','Rule Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Source_System','en','Source System');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Source_System','it','Source System');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_Close_Date','en','Target Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_Close_Date','it','Target Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_Remediation_Date','en','Target Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_Remediation_Date','it','Target Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_Unit','en','Business Unit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_Unit','it','Business Unit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_By','en','Updated By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_By','it','Updated By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_Date','en','Updated Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_Date','it','Updated Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Action_SPACE_Required_SPACE_By','en','Action Required By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Action_SPACE_Required_SPACE_By','it','Action Required By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_SPACE_Close_SPACE_Date','en','Actual Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_SPACE_Close_SPACE_Date','it','Actual Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_SPACE_Remediation_SPACE_Date','en','Actual Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_SPACE_Remediation_SPACE_Date','it','Actual Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BG_SPACE_Steward','en','BG Steward');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BG_SPACE_Steward','it','BG Steward');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Close_SPACE_Reason','en','Close Reason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Close_SPACE_Reason','it','Close Reason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Date_SPACE_Determined','en','Date Determined');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Date_SPACE_Determined','it','Date Determined');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Element_SPACE_Mapping','en','Element Mapping');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Element_SPACE_Mapping','it','Element Mapping');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Escalation_SPACE_Date','en','Escalation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Escalation_SPACE_Date','it','Escalation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Description','en','Exception Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Description','it','Exception Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Details','en','Exception Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Details','it','Exception Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_ID','en','Exception ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_ID','it','Exception ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Owner','en','Exception Owner');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Owner','it','Exception Owner');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Severity','en','Exception Severity');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Severity','it','Exception Severity');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Status','en','Exception Status');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Status','it','Exception Status');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Summary','en','Exception Summary');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SPACE_Summary','it','Exception Summary');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Final_SPACE_Disposition','en','Final Disposition');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Final_SPACE_Disposition','it','Final Disposition');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identified_SPACE_Date','en','Identified Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identified_SPACE_Date','it','Identified Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identifying_SPACE_Process','en','Identifying Process');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identifying_SPACE_Process','it','Identifying Process');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_SPACE_Amount','en','Impact Amount');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_SPACE_Amount','it','Impact Amount');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_SPACE_Description','en','Impact Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_SPACE_Description','it','Impact Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_SPACE_Associated_SPACE_Dollars','en','Invalid Associated Dollars');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_SPACE_Associated_SPACE_Dollars','it','Invalid Associated Dollars');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_SPACE_Count','en','Invalid Count');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_SPACE_Count','it','Invalid Count');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Matrix_SPACE_Rating','en','Matrix Rating');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Matrix_SPACE_Rating','it','Matrix Rating');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Open_SPACE_Page_SPACE_ID','en','Open Page ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Open_SPACE_Page_SPACE_ID','it','Open Page ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_SPACE_Description','en','Remediation Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_SPACE_Description','it','Remediation Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_SPACE_Owner_SPACE_Name','en','Remediation Owner Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_SPACE_Owner_SPACE_Name','it','Remediation Owner Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Root_SPACE_Cause','en','Root Cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Root_SPACE_Cause','it','Root Cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_SPACE_Description','en','Rule Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_SPACE_Description','it','Rule Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_SPACE_Name','en','Rule Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_SPACE_Name','it','Rule Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Source_SPACE_System','en','Source System');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Source_SPACE_System','it','Source System');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_SPACE_Close_SPACE_Date','en','Target Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_SPACE_Close_SPACE_Date','it','Target Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_SPACE_Remediation_SPACE_Date','en','Target Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_SPACE_Remediation_SPACE_Date','it','Target Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_SPACE_Unit','en','Business Unit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_SPACE_Unit','it','Business Unit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_SPACE_By','en','Updated By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_SPACE_By','it','Updated By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_SPACE_Date','en','Updated Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_SPACE_Date','it','Updated Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Action_SP_Required_SP_By','en','Action Required By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Action_SP_Required_SP_By','it','Action Required By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_SP_Close_SP_Date','en','Actual Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_SP_Close_SP_Date','it','Actual Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_SP_Remediation_SP_Date','en','Actual Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual_SP_Remediation_SP_Date','it','Actual Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BG_SP_Steward','en','BG Steward');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BG_SP_Steward','it','BG Steward');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_SP_Glossary_SP_Term_SP_Category','en','Business Glossary Term Category');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_SP_Glossary_SP_Term_SP_Category','it','Business Glossary Term Category');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_SP_Glossary_SP_Term_SP_Name','en','Business Glossary Term Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_SP_Glossary_SP_Term_SP_Name','it','Business Glossary Term Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Close_SP_Reason','en','Close Reason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Close_SP_Reason','it','Close Reason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Date_SP_Determined','en','Date Determined');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Date_SP_Determined','it','Date Determined');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Element_SP_Mapping','en','Element Mapping');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Element_SP_Mapping','it','Element Mapping');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Escalation_SP_Date','en','Escalation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Escalation_SP_Date','it','Escalation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Description','en','Exception Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Description','it','Exception Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Details','en','Exception Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Details','it','Exception Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_ID','en','Exception ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_ID','it','Exception ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Owner','en','Exception Owner');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Owner','it','Exception Owner');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Severity','en','Exception Severity');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Severity','it','Exception Severity');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Status','en','Exception Status');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Status','it','Exception Status');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Summary','en','Exception Summary');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception_SP_Summary','it','Exception Summary');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Final_SP_Disposition','en','Final Disposition');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Final_SP_Disposition','it','Final Disposition');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identified_SP_Date','en','Identified Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identified_SP_Date','it','Identified Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identifying_SP_Process','en','Identifying Process');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identifying_SP_Process','it','Identifying Process');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_SP_Amount','en','Impact Amount');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_SP_Amount','it','Impact Amount');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_SP_Description','en','Impact Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact_SP_Description','it','Impact Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_SP_Associated_SP_Dollars','en','Invalid Associated Dollars');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_SP_Associated_SP_Dollars','it','Invalid Associated Dollars');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_SP_Count','en','Invalid Count');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid_SP_Count','it','Invalid Count');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Matrix_SP_Rating','en','Matrix Rating');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Matrix_SP_Rating','it','Matrix Rating');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Open_SP_Page_SP_ID','en','Open Page ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Open_SP_Page_SP_ID','it','Open Page ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_SP_Description','en','Remediation Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_SP_Description','it','Remediation Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_SP_Owner_SP_Name','en','Remediation Owner Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation_SP_Owner_SP_Name','it','Remediation Owner Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Root_SP_Cause','en','Root Cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Root_SP_Cause','it','Root Cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_SP_Description','en','Rule Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_SP_Description','it','Rule Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_SP_Name','en','Rule Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule_SP_Name','it','Rule Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Source_SP_System','en','Source System');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Source_SP_System','it','Source System');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_SP_Close_SP_Date','en','Target Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_SP_Close_SP_Date','it','Target Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_SP_Remediation_SP_Date','en','Target Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target_SP_Remediation_SP_Date','it','Target Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_SP_Unit','en','Business Unit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business_SP_Unit','it','Business Unit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_SP_By','en','Updated By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_SP_By','it','Updated By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_SP_Date','en','Updated Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated_SP_Date','it','Updated Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Action-SP-Required-SP-By','en','Action Required By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Action-SP-Required-SP-By','it','Action Required By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual-SP-Close-SP-Date','en','Actual Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual-SP-Close-SP-Date','it','Actual Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual-SP-Remediation-SP-Date','en','Actual Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Actual-SP-Remediation-SP-Date','it','Actual Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BG-SP-Steward','en','BG Steward');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_BG-SP-Steward','it','BG Steward');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business-SP-Glossary-SP-Term-SP-Category','en','Business Glossary Term Category');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business-SP-Glossary-SP-Term-SP-Category','it','Business Glossary Term Category');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business-SP-Glossary-SP-Term-SP-Name','en','Business Glossary Term Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business-SP-Glossary-SP-Term-SP-Name','it','Business Glossary Term Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Close-SP-Reason','en','Close Reason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Close-SP-Reason','it','Close Reason');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Date-SP-Determined','en','Date Determined');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Date-SP-Determined','it','Date Determined');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Element-SP-Mapping','en','Element Mapping');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Element-SP-Mapping','it','Element Mapping');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Escalation-SP-Date','en','Escalation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Escalation-SP-Date','it','Escalation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Description','en','Exception Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Description','it','Exception Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Details','en','Exception Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Details','it','Exception Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-ID','en','Exception ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-ID','it','Exception ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Owner','en','Exception Owner');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Owner','it','Exception Owner');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Severity','en','Exception Severity');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Severity','it','Exception Severity');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Status','en','Exception Status');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Status','it','Exception Status');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Summary','en','Exception Summary');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Exception-SP-Summary','it','Exception Summary');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Final-SP-Disposition','en','Final Disposition');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Final-SP-Disposition','it','Final Disposition');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identified-SP-Date','en','Identified Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identified-SP-Date','it','Identified Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identifying-SP-Process','en','Identifying Process');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Identifying-SP-Process','it','Identifying Process');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact-SP-Amount','en','Impact Amount');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact-SP-Amount','it','Impact Amount');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact-SP-Description','en','Impact Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Impact-SP-Description','it','Impact Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid-SP-Associated-SP-Dollars','en','Invalid Associated Dollars');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid-SP-Associated-SP-Dollars','it','Invalid Associated Dollars');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid-SP-Count','en','Invalid Count');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Invalid-SP-Count','it','Invalid Count');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Matrix-SP-Rating','en','Matrix Rating');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Matrix-SP-Rating','it','Matrix Rating');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Open-SP-Page-SP-ID','en','Open Page ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Open-SP-Page-SP-ID','it','Open Page ID');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation-SP-Description','en','Remediation Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation-SP-Description','it','Remediation Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation-SP-Owner-SP-Name','en','Remediation Owner Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Remediation-SP-Owner-SP-Name','it','Remediation Owner Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Root-SP-Cause','en','Root Cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Root-SP-Cause','it','Root Cause');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule-SP-Description','en','Rule Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule-SP-Description','it','Rule Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule-SP-Name','en','Rule Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Rule-SP-Name','it','Rule Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Source-SP-System','en','Source System');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Source-SP-System','it','Source System');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target-SP-Close-SP-Date','en','Target Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target-SP-Close-SP-Date','it','Target Close Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target-SP-Remediation-SP-Date','en','Target Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Target-SP-Remediation-SP-Date','it','Target Remediation Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business-SP-Unit','en','Business Unit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Business-SP-Unit','it','Business Unit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated-SP-By','en','Updated By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated-SP-By','it','Updated By');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated-SP-Date','en','Updated Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_Updated-SP-Date','it','Updated Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_Qualify-taskform','en','Qualify-taskform');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('JPKIE_FORM_Qualify-taskform','it','Qualify-taskform');
