INSERT INTO pages (code,parentcode,pos) VALUES ('service','homepage',1);
INSERT INTO pages (code,parentcode,pos) VALUES ('login','service',3);
INSERT INTO pages (code,parentcode,pos) VALUES ('notfound','service',1);
INSERT INTO pages (code,parentcode,pos) VALUES ('errorpage','service',2);
INSERT INTO pages (code,parentcode,pos) VALUES ('homepage','homepage',-1);
INSERT INTO pages (code,parentcode,pos) VALUES ('case_widgets','homepage',2);
INSERT INTO pages (code,parentcode,pos) VALUES ('task_details','homepage',3);
INSERT INTO pages (code,parentcode,pos) VALUES ('new_process','homepage',4);
INSERT INTO pages (code,parentcode,pos) VALUES ('task_list','homepage',5);
